# Generated by Django 5.2.5 on 2025-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='task_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
